// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHel5LEx6B4Sm8wMPq8s_7Cz4mzn85Ko',
    appId: '1:1028983928262:android:a51b2d0d9272a75e5aaec7',
    messagingSenderId: '1028983928262',
    projectId: 'testingchat-6a4be',
    storageBucket: 'testingchat-6a4be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8h9fuEZv_zHwkr04A98KmrfJIK70ddR8',
    appId: '1:1028983928262:ios:c316774a74f380f15aaec7',
    messagingSenderId: '1028983928262',
    projectId: 'testingchat-6a4be',
    storageBucket: 'testingchat-6a4be.appspot.com',
    androidClientId: '1028983928262-4qb166vv9uqce4std6t9j0rplcob6qo6.apps.googleusercontent.com',
    iosClientId: '1028983928262-d5ar1ffn0kb74jpfm487eae67k2j2hmj.apps.googleusercontent.com',
    iosBundleId: 'com.duytq.flutterchatdemo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6WAUxWqA-dPn6RvFoijQpDF1W7Mz1z-Y',
    appId: '1:1028983928262:web:d0afaab4fb3793b75aaec7',
    messagingSenderId: '1028983928262',
    projectId: 'testingchat-6a4be',
    authDomain: 'testingchat-6a4be.firebaseapp.com',
    storageBucket: 'testingchat-6a4be.appspot.com',
  );

}